apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-frontend
  namespace: online-boutique
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: frontend
  delay:
    latency: '2000ms'
    correlation: '100'
    jitter: '0ms'
  duration: '60s'
