apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  namespace: online-boutique
  labels:
    app: coupon-service
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: coupon-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
