apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-coupon-f005
  namespace: chaos-mesh
spec:
  action: delay
  mode: one
  duration: 15m
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: coupon-service
  delay:
    latency: 3000ms
    jitter: 1000ms
    correlation: "50"
