apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-boutique-custom-services
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  namespaceSelector:
    matchNames:
      - online-boutique
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
